mongo:
    host: localhost 
    port: 27017
    db: crystals
    default_collection: repo
    default_collection_file_path: $HOME/matador-db

plotting:
    default_style: matador
    element_colours: config/vesta_colours.ini
