mongo:
    host: node1
    port: 27017
    db: crystals
    default_collection: repo
    default_collection_file_path: /home/morris/shared/structure_repository

plotting:
    default_style: matador
    element_colours: config/vesta_colours.ini
