# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mlevs/matador
options:
  size: 2x
pipelines:
  default:
    - step:
        script:
          - cp matador/tests/data/matador_pipelines_conf.yml $HOME/.matadorrc
          - pip install .[test]
          - pip install .[plotting]
          - py.test --cov-config .coveragerc --cov=matador --durations=0
          - codecov --token=$CODECOV_TOKEN
        services:
          - mongo
        caches:
            - pip

definitions: 
  services: 
    mongo: 
      image: mongo
