name: matador
channels:
    - conda-forge
    - matsci
dependencies:
    - python==3.6
    - numpy>=1.10
    - scipy>=1.0
    - periodictable
    - seekpath
    - python-ternary==1.0.3
    - psutil
    - spglib
    - matplotlib>=2.0
